# Add `build-natives` label to the pull request then run:
# git commit --allow-empty -m "Empty commit to build natives"
# git push

name: build-natives

on:
  pull_request:
    branches: [ master ]

jobs:
  windows:
    if: contains(github.event.pull_request.labels.*.name, 'build-natives')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-msvc
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: install
          args: xargo

      - run: |
          cargo update --manifest-path crypto/Cargo.toml
          rustup component add rust-src
          xargo build --target x86_64-pc-windows-msvc --release --manifest-path crypto/Cargo.toml
        env:
          RUSTFLAGS: "-C target-feature=+aes,+ssse3"
          RUST_BACKTRACE: 1

      - uses: actions/upload-artifact@master
        with:
          name: shiruka.dll
          path: crypto/target/x86_64-pc-windows-msvc/release/shiruka.dll
  linux:
    if: contains(github.event.pull_request.labels.*.name, 'build-natives')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install MingW
        run: sudo apt-get install -y tree binutils

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: install
          args: xargo

      - run: |
          cargo update --manifest-path crypto/Cargo.toml
          xargo build --target x86_64-unknown-linux-gnu --release --manifest-path crypto/Cargo.toml
        env:
          RUST_BACKTRACE: 1
          RUSTFLAGS: "-C target-feature=+aes,+ssse3"

      - run: strip -s -w -K Java_* crypto/target/x86_64-unknown-linux-gnu/release/libshiruka.so

      - uses: actions/upload-artifact@master
        with:
          name: libshiruka.so
          path: crypto/target/x86_64-unknown-linux-gnu/release/libshiruka.so
